### ISSUE TITLE
Delete Dependency on FeaturePotentialBending

### ISSUE THREAD

**Issue by Bondoki** [sunprancekid/LeMonADE_StiffCyclic#3]
You can safely remove the dependency of "FeatureExcludedVolumeSc" in the calculation of the bending potential.
The reason: every bond is guaranteed to have a minimum length of 2 due to bond vector set. Therefore, there will be no undefined behavior as there are no bonds of length zero also in the ideal case.

https://github.com/sunprancekid/LeMonADE_StiffCyclic/blob/7166b798cbd1b6280ddd20780d7c3708d5811f36/feature/FeaturePotentialBending.h#L225-L226

**Comment by sunprancekid** [comment]
This feature requirement has been removed from the bending potential feature.
